version: '3'
services:
  app:
    image: app
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
