# Generated by Django 3.0 on 2019-12-04 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='If this is checked, enabled to be randomly selected. If unchecked random selection is disabled, regardless of begin and end date below.', verbose_name='Enabled')),
                ('begin', models.DateTimeField(blank=True, help_text='Optional date when eligibility for random selection *begins*. If specified, random selection is disabled after this date. (Timezone: US/Pacific)', null=True, verbose_name='Begin Date')),
                ('end', models.DateTimeField(blank=True, help_text='Optional date when eligibility for random selection *ends*. If specified, random selection is disabled after this date. (Timezone: US/Pacific)', null=True, verbose_name='End Date')),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text="The weight (ie selection bias) for how likely random selection occurs, eg '1' is just as likely as all others,  '2' is 2x as likely, '3' is 3x as likely and so on.", verbose_name='Random Weight')),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Optional Name')),
                ('md5sum', models.CharField(max_length=32)),
                ('audio', models.FileField(upload_to='assets/', verbose_name='Audio File')),
            ],
            options={
                'verbose_name': 'Audio Asset',
                'verbose_name_plural': 'Audio Assets',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Category name of this asset rotation, eg 'ADs', 'Station IDs, 'Short Interviews', etc.", max_length=50, verbose_name='Rotation Name')),
                ('color', models.CharField(choices=[('ff8a80', 'Red'), ('ff80ab', 'Pink'), ('ea80fc', 'Purple'), ('b388ff', 'Deep Purple'), ('8c9eff', 'Indigo'), ('82b1ff', 'Blue'), ('80d8ff', 'Light Blue'), ('84ffff', 'Cyan'), ('a7ffeb', 'Teal'), ('b9f6ca', 'Green'), ('ccff90', 'Light Green'), ('f4ff81', 'Lime'), ('ffff8d', 'Yellow'), ('ffe57f', 'Amber'), ('ffd180', 'Orange'), ('ff9e80', 'Deep Orange')], default='80d8ff', help_text='Color that appears in the desktop software for assets in this rotation.', max_length=6, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Asset Rotation',
                'verbose_name_plural': 'Asset Rotations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StopSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='If this is checked, enabled to be randomly selected. If unchecked random selection is disabled, regardless of begin and end date below.', verbose_name='Enabled')),
                ('begin', models.DateTimeField(blank=True, help_text='Optional date when eligibility for random selection *begins*. If specified, random selection is disabled after this date. (Timezone: US/Pacific)', null=True, verbose_name='Begin Date')),
                ('end', models.DateTimeField(blank=True, help_text='Optional date when eligibility for random selection *ends*. If specified, random selection is disabled after this date. (Timezone: US/Pacific)', null=True, verbose_name='End Date')),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text="The weight (ie selection bias) for how likely random selection occurs, eg '1' is just as likely as all others,  '2' is 2x as likely, '3' is 3x as likely and so on.", verbose_name='Random Weight')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Stop Set',
                'verbose_name_plural': 'Stop Sets',
            },
        ),
        migrations.CreateModel(
            name='StopSetRotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Rotation', verbose_name='Asset Rotation')),
                ('stop_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.StopSet')),
            ],
            options={
                'verbose_name': 'Rotation Entry',
                'verbose_name_plural': 'Rotation Entries',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RotationAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Asset')),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Rotation', verbose_name='Rotation')),
            ],
            options={
                'verbose_name': 'Rotation',
                'verbose_name_plural': 'Rotations',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='rotation',
            name='stop_sets',
            field=models.ManyToManyField(through='backend.StopSetRotation', to='backend.StopSet'),
        ),
        migrations.AddField(
            model_name='asset',
            name='rotations',
            field=models.ManyToManyField(through='backend.RotationAsset', to='backend.Rotation'),
        ),
    ]
