CLIENT_CONFIG_KEYS = {
    # Map to default values
    'clickable_waveform': False,
    'fade_assets_ms': 0,
    'wait_interval_minutes': 20,
    'wait_interval_subtracts_stopset_playtime': False,
}

# Snarfed from https://materializecss.com/color.html
COLORS = (
    ('red', 'ff5252'),
    ('red-light', 'e57373'),
    ('red-dark', 'c62828'),
    ('pink', 'ff4081'),
    ('pink-light', 'f06292'),
    ('pink-dark', 'ad1457'),
    ('purple', 'e040fb'),
    ('purple-light', 'ba68c8'),
    ('purple-dark', '6a1b9a'),
    ('deep-purple', '7c4dff'),
    ('deep-purple-light', '9575cd'),
    ('deep-purple-dark', '4527a0'),
    ('indigo', '536dfe'),
    ('indigo-light', '7986cb'),
    ('indigo-dark', '283593'),
    ('blue', '448aff'),
    ('blue-light', '64b5f6'),
    ('blue-dark', '1565c0'),
    ('light-blue', '40c4ff'),
    ('light-blue-light', '4fc3f7'),
    ('light-blue-dark', '0277bd'),
    ('cyan', '18ffff'),
    ('cyan-light', '4dd0e1'),
    ('cyan-dark', '00838f'),
    ('teal', '64ffda'),
    ('teal-light', '4db6ac'),
    ('teal-dark', '00695c'),
    ('green', '69f0ae'),
    ('green-light', '81c784'),
    ('green-dark', '2e7d32'),
    ('light-green', 'b2ff59'),
    ('light-green-light', 'aed581'),
    ('light-green-dark', '558b2f'),
    ('lime', 'eeff41'),
    ('lime-light', 'dce775'),
    ('lime-dark', '9e9d24'),
    ('yellow', 'ffff00'),
    ('yellow-light', 'fff176'),
    ('yellow-dark', 'f9a825'),
    ('amber', 'ffd740'),
    ('amber-light', 'ffd54f'),
    ('amber-dark', 'ff8f00'),
    ('orange', 'ffab40'),
    ('orange-light', 'ffb74d'),
    ('orange-dark', 'ef6c00'),
    ('deep-orange', 'ff6e40'),
    ('deep-orange-light', 'ff8a65'),
    ('deep-orange-dark', 'd84315'),
)
